# Generated by Django 3.2.9 on 2021-11-11 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='imagen',
        ),
        migrations.AddField(
            model_name='usuario',
            name='photo',
            field=models.ImageField(default='images/deafualt.png', upload_to=''),
        ),
    ]
