# Generated by Django 3.2.9 on 2021-11-11 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0002_alter_product_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(default='', max_length=50)),
                ('producto', models.CharField(default='', max_length=50)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('total', models.PositiveIntegerField(default=1)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('photo', models.ImageField(default='images/deafualt1.png', upload_to='')),
            ],
        ),
    ]
