# Generated by Django 3.2.9 on 2021-11-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0003_carrito'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(default='', max_length=50)),
                ('nit', models.CharField(default='', max_length=10)),
                ('direccion', models.CharField(default='', max_length=50)),
                ('sucursal', models.CharField(default='', max_length=50)),
                ('vendedor', models.CharField(default='', max_length=50)),
                ('total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('forma_pago', models.CharField(choices=[('Debito_Credito', 'Tarjeta de Débito o Credito'), ('Efectivo', 'Pago Contra Entrega')], default='efectivo', max_length=100)),
                ('recepcion', models.DateTimeField(auto_now_add=True)),
                ('entrega', models.DateTimeField()),
            ],
        ),
    ]
