# Generated by Django 3.2.9 on 2021-11-11 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0004_venta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='recepcion',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='sucursal',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='vendedor',
        ),
    ]
