# Generated by Django 3.2.9 on 2021-11-11 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0008_orderline_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderline',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='user',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderLine',
        ),
    ]
