# Generated by Django 3.2.9 on 2021-11-12 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0009_auto_20211111_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(default='', max_length=50)),
                ('direccion', models.CharField(default='', max_length=50)),
                ('producto', models.CharField(default='', max_length=50)),
                ('total', models.IntegerField()),
                ('forma_pago', models.CharField(choices=[('Debito_Credito', 'Tarjeta de Débito o Credito'), ('Efectivo', 'Pago Contra Entrega')], default='efectivo', max_length=100)),
                ('entrega', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='venta',
            name='total1',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
