# Generated by Django 3.2.9 on 2021-11-12 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0010_auto_20211111_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='total1',
            field=models.IntegerField(default=0),
        ),
    ]
