# Generated by Django 3.2.9 on 2021-11-12 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0012_remove_venta_total1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordenes',
            name='total',
        ),
    ]
