# Generated by Django 3.2.9 on 2021-11-12 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0015_auto_20211111_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='numorden',
            field=models.IntegerField(default=0),
        ),
    ]
