# Generated by Django 3.2.9 on 2021-11-12 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0017_alter_venta_numorden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='numorden',
        ),
    ]
